self-hosted-runner:
  labels:
    - ci
    - bw1100
    - nmz1
    - nmz2
    - nmz3
    - nmz4
    - nmz5

config-variables:
  - LMCACHE_HCU_CI_ENABLED
  - LMCACHE_HCU_RUNNER_ISOLATED
  - LMCACHE_HCU_BASE_IMAGE
  - LMCACHE_HCU_BASE_IMAGE_ID
  - LMCACHE_HCU_ARCH
  - LMCACHE_HCU_CACHE_ROOT_NMZ1
  - LMCACHE_HCU_CACHE_ROOT_NMZ2
  - LMCACHE_HCU_CACHE_ROOT_NMZ3
  - LMCACHE_HCU_CACHE_ROOT_NMZ4
  - LMCACHE_HCU_CACHE_ROOT_NMZ5
