self-hosted-runner:
  labels:
    - hcu
    - hcu-ci-pr
    - bw1100
    - nmz4

config-variables:
  - LMCACHE_HCU_CI_ENABLED
  - LMCACHE_HCU_RUNNER_ISOLATED
  - LMCACHE_HCU_BASE_IMAGE
  - LMCACHE_HCU_ARCH
  - LMCACHE_HCU_CACHE_ROOT_NMZ4
